services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: tomyj/Forum-backend
    ports:
      - 6969:6969
  front:
    depends_on:
      - api
    build:
      context: .
      dockerfile: frontV2/Dockerfile
    image: tomyj/Forum-front
    ports:
      - 80:80