services:
  api:
    build:
      context: ./backend
      dockerfile: dockerfile
    image: tomyj/forum-backend
    ports:
      - 6969:6969
    networks:
      - default
  front:
    depends_on:
      - api
    build:
      context: ./frontV2
      dockerfile: dockerfile
    image: tomyj/forum-front
    ports:
      - 8080:8080
    networks:
      - default
networks:
  default