services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: tomyj/Forum-backend
    ports:
      - 6969:6969
  front:
    depends_on:
      - api
    build:
      context: ./frontV2
      dockerfile: Dockerfile
    image: tomyj/Forum-front
    ports:
      - 80:80