create TABLE IF NOT EXISTS User (
    ID_USER INTEGER PRIMARY KEY,
    USERNAME TEXT,
    USER_PASSWORD TEXT
);

create TABLE IF NOT EXISTS Post (
    ID_POST INTEGER PRIMARY KEY,
    TIMESTAMP TEXT,
    CONTENT TEXT,
    ID_USER INTEGER,
    FOREIGN KEY(ID_USER) REFERENCES User(ID_USER)
);